version: 2.1
jobs:
  build:
    docker:
      - image: docker:19.03.13

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t rambooreddy/circle-ci:latest .

      - run:
          name: Push Docker Image to Registry
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push rambooreddy/circle-ci:latest
